// <auto-generated />
using System;
using MentalHealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentalHealth.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentalHealth.Models.MentalHealthSymptoms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Anxiety")
                        .HasColumnType("real");

                    b.Property<float>("ConcentrationIssues")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Depression")
                        .HasColumnType("real");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EmotionalChanges")
                        .HasColumnType("real");

                    b.Property<float>("Fatigue")
                        .HasColumnType("real");

                    b.Property<float>("Hallucinations")
                        .HasColumnType("real");

                    b.Property<float>("Irritability")
                        .HasColumnType("real");

                    b.Property<float>("Paranoia")
                        .HasColumnType("real");

                    b.Property<float>("PhysicalSymptoms")
                        .HasColumnType("real");

                    b.Property<float>("SleepIssues")
                        .HasColumnType("real");

                    b.Property<float>("SocialWithdrawal")
                        .HasColumnType("real");

                    b.Property<float>("SubstanceUse")
                        .HasColumnType("real");

                    b.Property<float>("ThoughtPatterns")
                        .HasColumnType("real");

                    b.Property<float>("TraumaHistory")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MentalHealth.Models.TrainingDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationAccuracy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImportDate");

                    b.ToTable("TrainingData");
                });
#pragma warning restore 612, 618
        }
    }
}
